spring:
  application:
    name: lambkey-provider # 指定当前微服务的名称，方便将来调用当前微服务时能够找到

eureka:
  client:
    service-url:           # 配置当前微服务作为Eureka客户端访问Eureka服务器端时使用的地址
      defaultZone: http://localhost:5000/eureka/
server:
  port: 3000

# 监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
