server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

spring:
  application:
    name: lambkey-project-consumer
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

  redis:
    host: 127.0.0.1

  session:
    store-type: redis

cos:
  tencent:
    accesskey: AKIDCE2bv0qQlqgJisnS3PWO0NVN0NVN0NVN
    secretKey: f4GDvNaYKsBE3d1B6lBLGvLXUCeroVx9
    bucket: ap-guangzhou
    bucketName: lambkey-1309051782
    path: https://lambkey-1309051782.cos.ap-guangzhou.myqcloud.com