server:
  port: 2000

spring:
  application:
    name: lambkey-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/project_crowd?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

logging:
  level:
    lamb.key.crowd.mapper: debug
    lamb.key.crowd.test: debug


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml