server:
  port: 1000

spring:
  application:
    name: lambkey-eureka
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 自己就是注册中心，所以自己不注册自己
    fetch-registry: false       # 自己就是注册中心，所以不需要从注册中心取回信息
    service-url:
      defautZone: http://${eureka.instance.hostname}:${server.port}/eureka/


